spring.data.mongodb.uri=mongodb+srv://Malika_user:root%4012345@cluster0.unltyep.mongodb.net/journalDb?retryWrites=true&w=majority&appName=Cluster0
#logging.level.org.springframework.data.mongodb=DEBUG
#logging.level.org.mongodb.driver=DEBUG
spring.data.mongodb.auto-index-creation=true

#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=your_email@gmail.com
#spring.mail.password=your_app_password
#
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true





